---
swagger: "2.0"
info:
  description: "uber + google "
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "Uber"
  description: "obtencion de tiempo estimado de viaje a travez de lon y lat de inicio\
    \ y lon y lat de final"
  externalDocs:
    description: "Find out more"
    url: "https://developer.uber.com/docs/riders/references/api/v1.2/requests-estimate-post"
- name: "Google"
  description: "obtencion de lon y lat a travez de direccion"
- name: "user"
  description: "consultar tiempo estimado"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"

paths:
  /get_latlon:
    post:
      tags:
      - "Google"
      summary: "obtener coordenadas"
      description: ""
      operationId: "get_latlon_get"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "recibe un json con las direcciones y obtienes un json con las coordenads"
        required: true
        schema:
          $ref: "#/definitions/get_lat_lon"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.google_controller"
  /get_time:
    post:
      tags:
      - "Uber"
      summary: "obtener tiempo estimado con las locaciones"
      description: ""
      operationId: "get_time_post"
      consumes:
      - "application/json   "
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "recibe un json con coordenadas y entrega el tiempo en minutos"
        required: true
        schema:
          $ref: "#/definitions/estimated_time"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.uber_controller"
  /user:
    post:
      tags:
      - "User"
      summary: "uso de los 2 microservices"
      description: ""
      operationId: "get_estimated"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "recibe json con direcciones y entrega a otros servicios, recibes tiempo en minutos"
        required: true
        schema:
          $ref: "#/definitions/get_lat_lon"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
      
definitions:
  estimated_time:
    type: "object"
    properties:
      longitude_start:
        type: "number"
        
      latitude_start:
        type: "number"
        
      longitude_end:
        type: "number"
        
      latitude_end:
        type: "number"
        
    example:
      longitude_start: -122.411
      latitude_start: 37.770
      longitude_end: -122.405
      latitude_end: 37.791
  get_lat_lon:
    type: "object"
    properties:
      address:
        type: "string"
      number:
        type: "string"
      county:
        type: "string"
      city:
        type: "string"
      country:
        type: "string"
    example:
      inicio:
        address: "apoquindo"
        number: "4820"
        county: "las condes"
        city: "santiago"
        country: "chile"
      destino:
        address: "Antonio varas"
        number: "880"
        county: "providencia"
        city: "santiago"
        country: "chile"
        
      
